// <auto-generated />
using System;
using LibraryManagmentSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManagmentSystem.Migrations
{
    [DbContext(typeof(LibraryManagementContext))]
    [Migration("20220621190739_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryManagmentSystem.Models.AccountsInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LibraryManagmentSystem.Models.BooksInfo", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfCopies")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Philosopher's Stone",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 12,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Chamber of Secrets",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 16,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Prisoner of Azkaban",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 7,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Goblet of Fire",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 9,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Order of the Phoenix",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 6,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Half Blood Prince",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 8,
                            Publisher = "Bloomsbury Publishing"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "JK Rowling",
                            BookTitle = "Harry Potter and the Deathly Hallows",
                            Category = "Fiction",
                            ImageURl = " ",
                            IsAvailable = true,
                            NoOfCopies = 8,
                            Publisher = "Bloomsbury Publishing"
                        });
                });

            modelBuilder.Entity("LibraryManagmentSystem.Models.LendRequest", b =>
                {
                    b.Property<int>("LendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LendStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LendId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("LendRequests");
                });

            modelBuilder.Entity("LibraryManagmentSystem.Models.LendRequest", b =>
                {
                    b.HasOne("LibraryManagmentSystem.Models.BooksInfo", "BooksInfo")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagmentSystem.Models.AccountsInfo", "AccountsInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountsInfo");

                    b.Navigation("BooksInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
